// Generated by CoffeeScript 1.3.3
(function() {
  var Comment, Comments,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Comment = (function(_super) {

    __extends(Comment, _super);

    function Comment() {
      return Comment.__super__.constructor.apply(this, arguments);
    }

    Comment.prototype.urlRoot = "/api/v1/comments/";

    return Comment;

  })(Backbone.Model);

  Comments = (function(_super) {

    __extends(Comments, _super);

    function Comments() {
      return Comments.__super__.constructor.apply(this, arguments);
    }

    Comments.prototype.model = Comment;

    Comments.prototype.url = "/api/v1/comments/";

    Comments.prototype.parse = function(data) {
      return data.objects;
    };

    return Comments;

  })(Backbone.Collection);

}).call(this);
