// Generated by CoffeeScript 1.3.3
(function() {
  var Router,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.routes = {
      "": "main"
    };

    Router.prototype.main = function() {
      return window.pollsView = new window.app.Views.PollsView();
    };

    window.app.Routers.Router = Router;

    return Router;

  })(Backbone.Router);

}).call(this);
