// Generated by CoffeeScript 1.3.3
(function() {
  var Poll,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Poll = (function(_super) {

    __extends(Poll, _super);

    function Poll() {
      return Poll.__super__.constructor.apply(this, arguments);
    }

    Poll.prototype.defaults = {
      id: "10",
      pub_date: "2015-07-26T23:38:12.644701+00:00",
      question: "How to make this more amazing?",
      resource_uri: "/api/rest/polls/10/"
    };

    Poll.prototype.urlRoot = POLLS_API;

    return Poll;

  })(Backbone.Model);

  window.app.Models.Poll = Poll;

}).call(this);
