// Generated by CoffeeScript 1.3.3
(function() {
  var Poll, poll,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Poll = (function(_super) {

    __extends(Poll, _super);

    function Poll() {
      alert("This is a Model");
    }

    return Poll;

  })(Backbone.Model);

  poll = new Poll;

}).call(this);
