// Generated by CoffeeScript 1.3.3
(function() {

  window.app = {
    Views: {},
    Routers: {},
    Models: {},
    Collections: {},
    init: function() {
      console.log("app init");
      window.router = new window.app.Routers.Router();
      return Backbone.history.start();
    }
  };

  window.jst = {
    Poll: Handlebars.compile($("#poll_template").html())
  };

  jQuery(function() {
    return window.app.init();
  });

  console.log("Hello world");

}).call(this);
