// Generated by CoffeeScript 1.3.3
(function() {
  var PollsView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PollsView = (function(_super) {

    __extends(PollsView, _super);

    function PollsView() {
      return PollsView.__super__.constructor.apply(this, arguments);
    }

    PollsView.prototype.el = "#content";

    PollsView.prototype.initialize = function() {
      _.bindAll(this);
      this.collection = new window.app.Collections.Polls();
      this.collection.bind('add', this.appendItem);
      this.collection.bind('reset', this.addAll);
      this.collection.fetch();
      return this.render();
    };

    PollsView.prototype.render = function() {
      console.log("render polls_view");
      $(this.el).append('<button>Add List Item</button>');
      return $(this.el).append('<ul></ul>');
    };

    PollsView.prototype.addItem = function() {
      var poll;
      poll = new window.app.Models.Poll;
      this.collection.add(poll);
      return poll.save();
    };

    PollsView.prototype.appendItem = function(poll) {
      var poll_view;
      poll_view = new window.app.Views.PollView({
        model: poll
      });
      return this.$el.append(poll_view.render().el);
    };

    PollsView.prototype.addAll = function() {
      console.log("addAll");
      console.log(this.collection.models);
      return this.collection.each(this.appendItem);
    };

    PollsView.prototype.events = {
      'click button': 'addItem'
    };

    window.app.Views.PollsView = PollsView;

    return PollsView;

  })(Backbone.View);

}).call(this);
